name: Primer workflow

on: push

jobs:
  hola_mundo:
    runs-on: ubuntu-latest

    steps:
      - name: Bajar código
        uses: actions/checkout@v4
      - name: probar código
        run: python3 main.py
      - name: crear imagen docker
        run: docker build -t ulopeznovoa/holamundo .
      - name: probar contenedor
        run: docker run ulopeznovoa/holamundo
